eclipse/editdor

package.json

Adding missing URL in package.json

Adding missing URL

---

src/components/App/AppHeader/AppHeader.jsx

Adding Permalink generation and interpretation

---

public/index.html
public/manifest.json
src/assets/main.css
src/components/App/AppHeader/AppHeader.jsx
src/components/TDViewer/Action.jsx
src/components/TDViewer/AddAction.js
src/components/TDViewer/AddForm.jsx
src/components/TDViewer/Event.jsx
src/components/TDViewer/Form.jsx
src/components/TDViewer/OperationsSelections.js
src/components/TDViewer/Property.jsx
src/components/TDViewer/TDViewer.jsx
src/context/GlobalState.js
src/context/ediTDorContext.js
src/context/editorReducers.js
src/index.css
src/index.js
src/util.js

Added Features: 
- sorting of Properties, Actions, Events
- searching for Properties, Actions, Events
- Thing Forms rendering
- Thing Forms adding with wizard
- Thing Forms deletion
- PWA
Fixes: 
- Permalink is shorter.

Feature development 1

---

src/assets/main.css
src/components/TDViewer/Action.jsx
src/components/TDViewer/Event.jsx
src/components/TDViewer/Form.jsx
src/components/TDViewer/Property.jsx
src/components/TDViewer/SearchBar.jsx
src/components/TDViewer/TDViewer.jsx

Changes all currently used icons to a feather icon component. <br>
Updates visuals of search bars.

feat: switch to feather icons

---

src/components/InfoIcon/InfoTooltips.jsx
src/components/TDViewer/InteractionSection.jsx
src/components/TDViewer/TDViewer.jsx

Moved interaction specific logic into its own component.
Signed-off-by: Stefan Pfahler <stefan.pfahler@evosoft.com>

fix: null pointer exception on sort/search

---

.github/workflows/publish-to-gh-pages.yml
package.json

Fix deployment action to github pages

Fix deployment

---

README.md
src/components/App/AppFooter.jsx

update readme + footer with github link

---

src/components/App/AppHeader/AppHeader.jsx
src/components/Dialogs/ConvertTmDialog.jsx
src/components/Dialogs/CreateTdDialog.jsx
src/context/GlobalState.js
src/context/ediTDorContext.js
src/context/editorReducers.js

- Toggle TD/TM in the New menu
- Choose which interaction affordances should be exported from TM to TD
- Always export affordances from "tm:required" field
Signed-off-by: fatadel <fatadel@gmail.com>

feat: extend TM functionality

---

package-lock.json
package.json
src/components/App/App.css
src/components/App/AppHeader/AppHeader.jsx
src/components/Dialogs/AddLinkTdDialog.jsx
src/components/Dialogs/CreateTdDialog.jsx
src/components/Editor/Editor.jsx
src/components/InfoIcon/InfoTooltips.jsx
src/components/TDViewer/Link.jsx
src/components/TDViewer/TDViewer.jsx
src/context/GlobalState.js
src/context/ediTDorContext.js
src/context/editorReducers.js
src/util.js

- Add links by wizard
- visualizing links in both graph and list format
- Handling multiple things description

Features dev

---

src/components/TDViewer/TDViewer.jsx

fix: removing warning

---

src/components/App/App.css
src/components/App/AppHeader/AppHeader.jsx
src/components/Dialogs/AddLinkTdDialog.jsx
src/context/editorReducers.js
src/util.js

- Fixing the native file system API problem in firefox

fix: Open files in firefox

---

src/components/App/AppHeader/AppHeader.jsx

- Fixing file extension when saving files (on browser that doesn't support File System Access API)
- better filenames when saving files 
- Delete save button on browser that doesn't support File System Access API
- Adding Hyperlink to logo
- fixes #59 
- fixes #58

fixing saving issues/adding hyperLink to logo

---

src/components/Dialogs/DialogTemplate.jsx

- Adding shortcut CTRL + Enter to create tds/tms and adding affordances
- fixes #56

feat: adding shortcuts for creating tds/tms and adding affordances

---

src/components/Editor/Editor.jsx

- Fix warnings for Thing model
- Fixes #62

fix Thing model warnings

---

src/components/Dialogs/AddPropertyDialog.jsx

- Adding items field for array types in properties
- Adding properties field for object types in properties
- fixes #61

feat: adding items for array and properties for object types

---

src/components/Dialogs/AddLinkTdDialog.jsx
src/components/Dialogs/DialogTemplate.jsx
src/components/Dialogs/ShareDialog.jsx

- Improving the Sharing pop-up window
- Removing error message when fetching a linked resource to the Td
- fixes #63 
- fixes #60

Ux improvement

---

package.json
src/components/App/App.jsx

Switching Viewer to the right since this is the most used workflow

feat: switch windows of editor and viewer

---

package-lock.json
package.json
src/assets/main.css
src/components/App/AppFooter.jsx
src/components/App/AppHeader/AppHeader.jsx
src/components/Dialogs/AddLinkTdDialog.jsx
src/components/Dialogs/ConvertTmDialog.jsx
src/components/Dialogs/CreateTdDialog.jsx
src/components/TDViewer/TDViewer.jsx
src/context/GlobalState.js
src/context/ediTDorContext.js
src/context/editorReducers.js
src/index.css
src/services/fileTdService.js
src/util.js

- add loading animation for saving/opening
- add indicator for "synched changes"
- fix showing convert to TD button
- restructure file operation code into own file

fix: issues with save button/thing model

---

src/components/TDViewer/TDViewer.jsx

We can create TMs and the buttons is not called _New TD_ but just _New_

Changing the starter text to reflect the current way

---

README.md

Netlify can be tested with this as well.

Simple Readme Improvements
